name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main
      - development
    paths:
      - "backend/**"
  pull_request:
    branches:
      - main
      - development
    paths:
      - "backend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.20.4" # align with EC2 instance node version. 20 is recommended?

      - name: Cache Node.js modules # to speed up dependencies installation
        uses: actions/cache@v3 # v4 is available, but for node 20
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      #- name: Run tests
      #  run: npm test

      - name: Deploy to EC2
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd ~/GlucoFit/backend
            git pull origin main
            npm install
            npm run build
            pm2 restart all

      - name: Restart Nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            sudo systemctl restart nginx
